<?php
namespace AppBundle\foundation ;

use Doctrine\ORM\EntityRepository;

/**
 * FiremanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class BaseRepository extends EntityRepository
{

//--------------------------------------------------------------------------
// pko - this is the JSON part with JMSSerializerBundle
//--------------------------------------------------------------------------
  public function getEntitiesWithPagination($page, $pagesize, $filters, $order){
      $entities = $this->getEntities($page, $pagesize, $filters, $order) ;
      $pagination = array(
            'page' => $page,
            'pages_count' => ceil($this->queryCount / $pagesize),
            'records_count' => $this->queryCount,
            'pagesize' => $pagesize,
            'entities' => $entities
        );
    return $pagination ;
    }
  public function getEntities($page, $pagesize, $filters, $order){
        $qb = $this->getEntitiesQb($page, $pagesize, $filters, $order) ;
        $qb->setMaxResults($pagesize);
        $qb->setFirstResult( $page * $pagesize);
        $query = $qb->getQuery();
        $entities = $query->getResult() ;

        $qb2 = $this->getEntitiesQb($page, $pagesize, $filters, $order)  ;
        $qb2->select("COUNT('u')") ;

        $this->queryCount = intval($qb2->getQuery()->getSingleScalarResult()) ;
        return $entities ;
    }
  public function getEntitiesQb($page, $pagesize, $filters, $order){
        $count = 0 ;
        $qb = $this->createQueryBuilder("u") ;
        $qb = $this->addFilters($qb, $filters) ;
        $qb = $this->addSorts($qb, $order) ;
        return $qb ;
    }

//--------------------------------------------------------------------------
// pko - this is the JSON part with JMSSerializerBundle
//--------------------------------------------------------------------------
  abstract public function addSorts($qb, $orders) ;
    /*{
      return $qb ;
    }*/

  abstract public function addFilters($qb, $filters) ;/*{
        return $qb ;
    }*/


}
